/**
 * Fallback launch schedule for the Cape Canaveral spaceport region.
 *
 * The app tries the live Launch Library 2 API first (see app.js). If the
 * network is unavailable, this curated, plausible schedule is used so the
 * page always looks alive. Dates are in UTC (ISO 8601).
 *
 * "status" values:
 *   GO    – on the range schedule, expected to fly
 *   TBD   – targeting a window, date may slip
 *   HOLD  – temporarily paused (weather / technical)
 *   NET   – "no earlier than", early planning
 */
window.FALLBACK_LAUNCHES = [
  {
    name: "Starlink Group 12-5",
    provider: "SpaceX",
    rocket: "Falcon 9 Block 5",
    pad: "SLC-40",
    site: "Cape Canaveral SFS",
    net: "2026-06-17T23:14:00Z",
    window: "Instantaneous",
    status: "GO",
    mission: "Batch of 23 V2 Mini satellites for the Starlink broadband constellation.",
    orbit: "Low Earth Orbit",
    payloadKg: 17600,
    booster: "B1083 · 14th flight · droneship landing",
  },
  {
    name: "USSF-87 (GSSAP)",
    provider: "ULA",
    rocket: "Vulcan Centaur VC4S",
    pad: "SLC-41",
    site: "Cape Canaveral SFS",
    net: "2026-06-19T06:30:00Z",
    window: "04:30–07:00 UTC",
    status: "GO",
    mission: "Geosynchronous Space Situational Awareness Program payloads for the U.S. Space Force.",
    orbit: "Near-geosynchronous",
    payloadKg: 5000,
    booster: "Expendable · 4 solid boosters",
  },
  {
    name: "Crew-12",
    provider: "SpaceX / NASA",
    rocket: "Falcon 9 Block 5",
    pad: "LC-39A",
    site: "Kennedy Space Center",
    net: "2026-06-22T13:48:00Z",
    window: "Instantaneous",
    status: "GO",
    mission: "Crew Dragon 'Endeavour' carries four astronauts to the International Space Station for Expedition 74.",
    orbit: "ISS · 51.6° inclination",
    payloadKg: 12500,
    booster: "B1085 · 6th flight · LZ-1 return",
  },
  {
    name: "Project Kuiper KA-9",
    provider: "Amazon / ULA",
    rocket: "Atlas V 551",
    pad: "SLC-41",
    site: "Cape Canaveral SFS",
    net: "2026-06-25T11:00:00Z",
    window: "2-hour window",
    status: "TBD",
    mission: "Production batch of Kuiper broadband satellites for Amazon's internet constellation.",
    orbit: "Low Earth Orbit",
    payloadKg: 9600,
    booster: "Expendable · 5 solid boosters",
  },
  {
    name: "Starlink Group 10-22",
    provider: "SpaceX",
    rocket: "Falcon 9 Block 5",
    pad: "SLC-40",
    site: "Cape Canaveral SFS",
    net: "2026-06-27T02:40:00Z",
    window: "Instantaneous",
    status: "GO",
    mission: "Another 23-satellite Starlink batch expanding global coverage.",
    orbit: "Low Earth Orbit",
    payloadKg: 17600,
    booster: "B1090 · 9th flight · droneship landing",
  },
  {
    name: "GOES-U Follow-on",
    provider: "NASA / NOAA",
    rocket: "Falcon Heavy",
    pad: "LC-39A",
    site: "Kennedy Space Center",
    net: "2026-07-01T21:16:00Z",
    window: "21:16–23:16 UTC",
    status: "TBD",
    mission: "Next-generation geostationary weather observatory for continuous hemispheric monitoring.",
    orbit: "Geostationary Transfer",
    payloadKg: 5200,
    booster: "Twin side cores RTLS · center core expended",
  },
  {
    name: "Vulcan USSF-112",
    provider: "ULA",
    rocket: "Vulcan Centaur VC6L",
    pad: "SLC-41",
    site: "Cape Canaveral SFS",
    net: "2026-07-05T00:00:00Z",
    window: "TBD",
    status: "NET",
    mission: "Classified national security payload to a high-energy orbit.",
    orbit: "Direct GEO insertion",
    payloadKg: 6800,
    booster: "Expendable · 6 solid boosters",
  },
  {
    name: "Polaris / Dragon Free-Flyer",
    provider: "SpaceX",
    rocket: "Falcon 9 Block 5",
    pad: "LC-39A",
    site: "Kennedy Space Center",
    net: "2026-07-09T08:00:00Z",
    window: "Instantaneous",
    status: "NET",
    mission: "Commercial human spaceflight mission featuring extended free-flight operations.",
    orbit: "High Earth Orbit",
    payloadKg: 12000,
    booster: "B1091 · 3rd flight · droneship landing",
  },
  {
    name: "Starlink Group 12-9",
    provider: "SpaceX",
    rocket: "Falcon 9 Block 5",
    pad: "SLC-40",
    site: "Cape Canaveral SFS",
    net: "2026-07-12T19:05:00Z",
    window: "Instantaneous",
    status: "NET",
    mission: "Routine Starlink deployment maintaining constellation density.",
    orbit: "Low Earth Orbit",
    payloadKg: 17600,
    booster: "TBD · droneship landing",
  },
  {
    name: "CLPS Lunar Lander",
    provider: "SpaceX / Firefly",
    rocket: "Falcon 9 Block 5",
    pad: "SLC-40",
    site: "Cape Canaveral SFS",
    net: "2026-07-18T05:30:00Z",
    window: "Instantaneous",
    status: "NET",
    mission: "Commercial Lunar Payload Services lander carrying NASA science instruments toward the Moon.",
    orbit: "Trans-Lunar Injection",
    payloadKg: 6200,
    booster: "Expendable · no recovery",
  },
];
